// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/bluefin-payconex-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"account_updater | account_updater_schedule | account_updater_schedule_with_result | account_updater_subscription_with_result | account_updater_update | api_key | apple_pay_merchant_detail | apple_pay_session | dynamic_descriptor | i_frame_create_instance | i_frame_instance | iframe | init | list_api_key_scopes_entry | payment_iframe | three_d_secure_auth | three_d_secure_browser_init | three_d_secure_status | transaction_detail | webhook"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.BluefinPayconexSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-payconex_list",
		Description: "List records from BluefinPayconex. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-payconex_load",
		Description: "Load a single record from BluefinPayconex. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.BluefinPayconexSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinPayconexSDK, name string) (sdk.BluefinPayconexEntity, error) {
	switch strings.ToLower(name) {
	case "account_updater":
		return client.AccountUpdater(nil), nil
	case "account_updater_schedule":
		return client.AccountUpdaterSchedule(nil), nil
	case "account_updater_schedule_with_result":
		return client.AccountUpdaterScheduleWithResult(nil), nil
	case "account_updater_subscription_with_result":
		return client.AccountUpdaterSubscriptionWithResult(nil), nil
	case "account_updater_update":
		return client.AccountUpdaterUpdate(nil), nil
	case "api_key":
		return client.ApiKey(nil), nil
	case "apple_pay_merchant_detail":
		return client.ApplePayMerchantDetail(nil), nil
	case "apple_pay_session":
		return client.ApplePaySession(nil), nil
	case "dynamic_descriptor":
		return client.DynamicDescriptor(nil), nil
	case "i_frame_create_instance":
		return client.IFrameCreateInstance(nil), nil
	case "i_frame_instance":
		return client.IFrameInstance(nil), nil
	case "iframe":
		return client.Iframe(nil), nil
	case "init":
		return client.Init(nil), nil
	case "list_api_key_scopes_entry":
		return client.ListApiKeyScopesEntry(nil), nil
	case "payment_iframe":
		return client.PaymentIframe(nil), nil
	case "three_d_secure_auth":
		return client.ThreeDSecureAuth(nil), nil
	case "three_d_secure_browser_init":
		return client.ThreeDSecureBrowserInit(nil), nil
	case "three_d_secure_status":
		return client.ThreeDSecureStatus(nil), nil
	case "transaction_detail":
		return client.TransactionDetail(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
