(* BluefinPayconex SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* AccountUpdater entity bound to a client:  account_updater client entopts *)
let account_updater (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_account_updater.make client entopts

(* AccountUpdaterSchedule entity bound to a client:  account_updater_schedule client entopts *)
let account_updater_schedule (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_account_updater_schedule.make client entopts

(* AccountUpdaterScheduleWithResult entity bound to a client:  account_updater_schedule_with_result client entopts *)
let account_updater_schedule_with_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_account_updater_schedule_with_result.make client entopts

(* AccountUpdaterSubscriptionWithResult entity bound to a client:  account_updater_subscription_with_result client entopts *)
let account_updater_subscription_with_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_account_updater_subscription_with_result.make client entopts

(* AccountUpdaterUpdate entity bound to a client:  account_updater_update client entopts *)
let account_updater_update (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_account_updater_update.make client entopts

(* ApiKey entity bound to a client:  api_key client entopts *)
let api_key (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_api_key.make client entopts

(* ApplePayMerchantDetail entity bound to a client:  apple_pay_merchant_detail client entopts *)
let apple_pay_merchant_detail (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_apple_pay_merchant_detail.make client entopts

(* ApplePaySession entity bound to a client:  apple_pay_session client entopts *)
let apple_pay_session (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_apple_pay_session.make client entopts

(* DynamicDescriptor entity bound to a client:  dynamic_descriptor client entopts *)
let dynamic_descriptor (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_dynamic_descriptor.make client entopts

(* IFrameCreateInstance entity bound to a client:  i_frame_create_instance client entopts *)
let i_frame_create_instance (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_i_frame_create_instance.make client entopts

(* IFrameInstance entity bound to a client:  i_frame_instance client entopts *)
let i_frame_instance (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_i_frame_instance.make client entopts

(* Iframe entity bound to a client:  iframe client entopts *)
let iframe (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_iframe.make client entopts

(* Init entity bound to a client:  init client entopts *)
let init (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_init.make client entopts

(* ListApiKeyScopesEntry entity bound to a client:  list_api_key_scopes_entry client entopts *)
let list_api_key_scopes_entry (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_list_api_key_scopes_entry.make client entopts

(* PaymentIframe entity bound to a client:  payment_iframe client entopts *)
let payment_iframe (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_payment_iframe.make client entopts

(* ThreeDSecureAuth entity bound to a client:  three_d_secure_auth client entopts *)
let three_d_secure_auth (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_three_d_secure_auth.make client entopts

(* ThreeDSecureBrowserInit entity bound to a client:  three_d_secure_browser_init client entopts *)
let three_d_secure_browser_init (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_three_d_secure_browser_init.make client entopts

(* ThreeDSecureStatus entity bound to a client:  three_d_secure_status client entopts *)
let three_d_secure_status (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_three_d_secure_status.make client entopts

(* TransactionDetail entity bound to a client:  transaction_detail client entopts *)
let transaction_detail (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transaction_detail.make client entopts

(* Webhook entity bound to a client:  webhook client entopts *)
let webhook (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_webhook.make client entopts
