-- BluefinPayconex SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , account_updater
  , account_updater_schedule
  , account_updater_schedule_with_result
  , account_updater_subscription_with_result
  , account_updater_update
  , api_key
  , apple_pay_merchant_detail
  , apple_pay_session
  , dynamic_descriptor
  , i_frame_create_instance
  , i_frame_instance
  , iframe
  , init
  , list_api_key_scopes_entry
  , payment_iframe
  , three_d_secure_auth
  , three_d_secure_browser_init
  , three_d_secure_status
  , transaction_detail
  , webhook
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The AccountUpdater entity bound to this client.
account_updater :: Client -> Value -> IO Entity
account_updater client entopts = F.makeEntity client "account_updater" entopts

-- | The AccountUpdaterSchedule entity bound to this client.
account_updater_schedule :: Client -> Value -> IO Entity
account_updater_schedule client entopts = F.makeEntity client "account_updater_schedule" entopts

-- | The AccountUpdaterScheduleWithResult entity bound to this client.
account_updater_schedule_with_result :: Client -> Value -> IO Entity
account_updater_schedule_with_result client entopts = F.makeEntity client "account_updater_schedule_with_result" entopts

-- | The AccountUpdaterSubscriptionWithResult entity bound to this client.
account_updater_subscription_with_result :: Client -> Value -> IO Entity
account_updater_subscription_with_result client entopts = F.makeEntity client "account_updater_subscription_with_result" entopts

-- | The AccountUpdaterUpdate entity bound to this client.
account_updater_update :: Client -> Value -> IO Entity
account_updater_update client entopts = F.makeEntity client "account_updater_update" entopts

-- | The ApiKey entity bound to this client.
api_key :: Client -> Value -> IO Entity
api_key client entopts = F.makeEntity client "api_key" entopts

-- | The ApplePayMerchantDetail entity bound to this client.
apple_pay_merchant_detail :: Client -> Value -> IO Entity
apple_pay_merchant_detail client entopts = F.makeEntity client "apple_pay_merchant_detail" entopts

-- | The ApplePaySession entity bound to this client.
apple_pay_session :: Client -> Value -> IO Entity
apple_pay_session client entopts = F.makeEntity client "apple_pay_session" entopts

-- | The DynamicDescriptor entity bound to this client.
dynamic_descriptor :: Client -> Value -> IO Entity
dynamic_descriptor client entopts = F.makeEntity client "dynamic_descriptor" entopts

-- | The IFrameCreateInstance entity bound to this client.
i_frame_create_instance :: Client -> Value -> IO Entity
i_frame_create_instance client entopts = F.makeEntity client "i_frame_create_instance" entopts

-- | The IFrameInstance entity bound to this client.
i_frame_instance :: Client -> Value -> IO Entity
i_frame_instance client entopts = F.makeEntity client "i_frame_instance" entopts

-- | The Iframe entity bound to this client.
iframe :: Client -> Value -> IO Entity
iframe client entopts = F.makeEntity client "iframe" entopts

-- | The Init entity bound to this client.
init :: Client -> Value -> IO Entity
init client entopts = F.makeEntity client "init" entopts

-- | The ListApiKeyScopesEntry entity bound to this client.
list_api_key_scopes_entry :: Client -> Value -> IO Entity
list_api_key_scopes_entry client entopts = F.makeEntity client "list_api_key_scopes_entry" entopts

-- | The PaymentIframe entity bound to this client.
payment_iframe :: Client -> Value -> IO Entity
payment_iframe client entopts = F.makeEntity client "payment_iframe" entopts

-- | The ThreeDSecureAuth entity bound to this client.
three_d_secure_auth :: Client -> Value -> IO Entity
three_d_secure_auth client entopts = F.makeEntity client "three_d_secure_auth" entopts

-- | The ThreeDSecureBrowserInit entity bound to this client.
three_d_secure_browser_init :: Client -> Value -> IO Entity
three_d_secure_browser_init client entopts = F.makeEntity client "three_d_secure_browser_init" entopts

-- | The ThreeDSecureStatus entity bound to this client.
three_d_secure_status :: Client -> Value -> IO Entity
three_d_secure_status client entopts = F.makeEntity client "three_d_secure_status" entopts

-- | The TransactionDetail entity bound to this client.
transaction_detail :: Client -> Value -> IO Entity
transaction_detail client entopts = F.makeEntity client "transaction_detail" entopts

-- | The Webhook entity bound to this client.
webhook :: Client -> Value -> IO Entity
webhook client entopts = F.makeEntity client "webhook" entopts

