;; BluefinPayconex SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.account_updater :as e-account_updater]
            [sdk.entity.account_updater_schedule :as e-account_updater_schedule]
            [sdk.entity.account_updater_schedule_with_result :as e-account_updater_schedule_with_result]
            [sdk.entity.account_updater_subscription_with_result :as e-account_updater_subscription_with_result]
            [sdk.entity.account_updater_update :as e-account_updater_update]
            [sdk.entity.api_key :as e-api_key]
            [sdk.entity.apple_pay_merchant_detail :as e-apple_pay_merchant_detail]
            [sdk.entity.apple_pay_session :as e-apple_pay_session]
            [sdk.entity.dynamic_descriptor :as e-dynamic_descriptor]
            [sdk.entity.i_frame_create_instance :as e-i_frame_create_instance]
            [sdk.entity.i_frame_instance :as e-i_frame_instance]
            [sdk.entity.iframe :as e-iframe]
            [sdk.entity.init :as e-init]
            [sdk.entity.list_api_key_scopes_entry :as e-list_api_key_scopes_entry]
            [sdk.entity.payment_iframe :as e-payment_iframe]
            [sdk.entity.three_d_secure_auth :as e-three_d_secure_auth]
            [sdk.entity.three_d_secure_browser_init :as e-three_d_secure_browser_init]
            [sdk.entity.three_d_secure_status :as e-three_d_secure_status]
            [sdk.entity.transaction_detail :as e-transaction_detail]
            [sdk.entity.webhook :as e-webhook]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; AccountUpdater accessor: (account_updater client data)
(defn account_updater [client data] (e-account_updater/make client data))

;; AccountUpdaterSchedule accessor: (account_updater_schedule client data)
(defn account_updater_schedule [client data] (e-account_updater_schedule/make client data))

;; AccountUpdaterScheduleWithResult accessor: (account_updater_schedule_with_result client data)
(defn account_updater_schedule_with_result [client data] (e-account_updater_schedule_with_result/make client data))

;; AccountUpdaterSubscriptionWithResult accessor: (account_updater_subscription_with_result client data)
(defn account_updater_subscription_with_result [client data] (e-account_updater_subscription_with_result/make client data))

;; AccountUpdaterUpdate accessor: (account_updater_update client data)
(defn account_updater_update [client data] (e-account_updater_update/make client data))

;; ApiKey accessor: (api_key client data)
(defn api_key [client data] (e-api_key/make client data))

;; ApplePayMerchantDetail accessor: (apple_pay_merchant_detail client data)
(defn apple_pay_merchant_detail [client data] (e-apple_pay_merchant_detail/make client data))

;; ApplePaySession accessor: (apple_pay_session client data)
(defn apple_pay_session [client data] (e-apple_pay_session/make client data))

;; DynamicDescriptor accessor: (dynamic_descriptor client data)
(defn dynamic_descriptor [client data] (e-dynamic_descriptor/make client data))

;; IFrameCreateInstance accessor: (i_frame_create_instance client data)
(defn i_frame_create_instance [client data] (e-i_frame_create_instance/make client data))

;; IFrameInstance accessor: (i_frame_instance client data)
(defn i_frame_instance [client data] (e-i_frame_instance/make client data))

;; Iframe accessor: (iframe client data)
(defn iframe [client data] (e-iframe/make client data))

;; Init accessor: (init client data)
(defn init [client data] (e-init/make client data))

;; ListApiKeyScopesEntry accessor: (list_api_key_scopes_entry client data)
(defn list_api_key_scopes_entry [client data] (e-list_api_key_scopes_entry/make client data))

;; PaymentIframe accessor: (payment_iframe client data)
(defn payment_iframe [client data] (e-payment_iframe/make client data))

;; ThreeDSecureAuth accessor: (three_d_secure_auth client data)
(defn three_d_secure_auth [client data] (e-three_d_secure_auth/make client data))

;; ThreeDSecureBrowserInit accessor: (three_d_secure_browser_init client data)
(defn three_d_secure_browser_init [client data] (e-three_d_secure_browser_init/make client data))

;; ThreeDSecureStatus accessor: (three_d_secure_status client data)
(defn three_d_secure_status [client data] (e-three_d_secure_status/make client data))

;; TransactionDetail accessor: (transaction_detail client data)
(defn transaction_detail [client data] (e-transaction_detail/make client data))

;; Webhook accessor: (webhook client data)
(defn webhook [client data] (e-webhook/make client data))
