;; BluefinPayconex SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "account_updater" (vs/jm
        "fields" (vs/jt)
        "name" "account_updater"
        "op" (vs/jm
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 1
                      "kind" "param"
                      "name" "record_id"
                      "orig" "record_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 2
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}/records/{recordId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}"
                  "records"
                  "{record_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "recordId" "record_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "record_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "DELETE"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "subscription")
            (vs/jt
              "account"
              "subscription"
              "record"))))
      "account_updater_schedule" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "enabled"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "period_date"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "period_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_format"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "token"
            "req" true
            "type" "`$ARRAY`"))
        "name" "account_updater_schedule"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/account-updater/payconex/subscribe"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "payconex"
                  "subscribe")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "account_updater_schedule_with_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "card"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "created_at"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "enabled"
            "op" (vs/jm
              "list" (vs/jm
                "req" true
                "type" "`$BOOLEAN`"))
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "expiry"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "most_recent_update"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "period_date"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "period_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "response_format"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "token"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "type"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "updated_at"
            "req" true
            "type" "`$STRING`"))
        "name" "account_updater_schedule_with_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/account-updater/pan/subscribe"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "pan"
                  "subscribe")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/account-updater/shieldconex/subscribe"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "shieldconex"
                  "subscribe")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "schedule_id"
                      "orig" "schedule_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{account}/account-updater/schedules/{scheduleId}/results"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "schedules"
                  "{schedule_id}"
                  "results")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "scheduleId" "schedule_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "schedule_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account")
            (vs/jt
              "account"
              "schedule"))))
      "account_updater_subscription_with_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "created_at"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "enabled"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "period_date"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "period_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "record"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "response_format"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "template_ref"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "updated_at"
            "req" false
            "type" "`$STRING`"))
        "name" "account_updater_subscription_with_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}/pan"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}"
                  "pan")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}/payconex"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}"
                  "payconex")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}/shieldconex"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}"
                  "shieldconex")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "css_42ffe2fd59e74d719970f1c966430323"
                      "index$" 1
                      "kind" "param"
                      "name" "subscription_id"
                      "orig" "subscription_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{account}/account-updater/subscriptions/{subscriptionId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "subscriptions"
                  "{subscription_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "subscriptionId" "subscription_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "subscription_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "subscription"))))
      "account_updater_update" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "account_updater_schedule_record_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "format"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "new_expiry"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "new_token"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "old_expiry"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "old_token"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "recurring_schedule"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "update_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "updated_at"
            "req" false
            "type" "`$STRING`"))
        "name" "account_updater_update"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "update_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{account}/account-updater/updates/{updateId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "account-updater"
                  "updates"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "account" "account_id"
                    "updateId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "api_key" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "account"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "enabled"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "expires_at"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "expires_in"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "label"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "method"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "scope"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$ARRAY`"))
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "secret"
            "req" false
            "type" "`$STRING`"))
        "name" "api_key"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/api-keys"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "api-keys")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 25
                      "kind" "query"
                      "name" "limit"
                      "orig" "limit"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 5
                      "kind" "query"
                      "name" "page"
                      "orig" "page"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" "words to search"
                      "kind" "query"
                      "name" "query"
                      "orig" "query"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/api-keys"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "api-keys")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "limit"
                    "page"
                    "query"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "api_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "resource_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/api-keys/{resourceId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "api-keys"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "resourceId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "api_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "resource_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/api/v4/accounts/{accountId}/api-keys/{resourceId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "api-keys"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "resourceId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "api_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "resource_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{accountId}/api-keys/{resourceId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "api-keys"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "resourceId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "apple_pay_merchant_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "domain"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "merchant_url"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "partner_merchant_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "payconex_account_id"
            "req" true
            "type" "`$STRING`"))
        "name" "apple_pay_merchant_detail"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/applePay/enrollment"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "applePay"
                  "enrollment")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/applePay/enrollment"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "applePay"
                  "enrollment")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "apple_pay_session" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "display_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "domain_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "epoch_timestamp"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "expires_at"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "merchant_identifier"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "merchant_session_identifier"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "nonce"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "operational_analytics_identifier"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "referrer"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "retry"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "signature"
            "req" false
            "type" "`$STRING`"))
        "name" "apple_pay_session"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$INTEGER`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/applePay/session"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "applePay"
                  "session")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "dynamic_descriptor" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "city"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "descriptor"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "state"
            "req" false
            "type" "`$STRING`"))
        "name" "dynamic_descriptor"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/dynamic_descriptors"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "dynamic_descriptors")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 25
                      "kind" "query"
                      "name" "limit"
                      "orig" "limit"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" 5
                      "kind" "query"
                      "name" "page"
                      "orig" "page"
                      "reqd" false
                      "type" "`$INTEGER`")
                    (vs/jm
                      "active" true
                      "example" "words to search"
                      "kind" "query"
                      "name" "query"
                      "orig" "query"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/dynamic_descriptors"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "dynamic_descriptors")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "limit"
                    "page"
                    "query"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ddesc_1669911404412ae74cd5eef8f463495d6b"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/dynamic_descriptors/{id}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "dynamic_descriptors"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ddesc_1669911404412ae74cd5eef8f463495d6b"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/api/v4/accounts/{accountId}/dynamic_descriptors/{id}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "dynamic_descriptors"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 180000027666
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ddesc_1669911404412ae74cd5eef8f463495d6b"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{accountId}/dynamic_descriptors/{id}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "dynamic_descriptors"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "i_frame_create_instance" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "amount"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "currency"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "customer"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "initialize_transaction"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "label"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "language"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "timeout"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "token"
            "req" false
            "type" "`$ARRAY`"))
        "name" "i_frame_create_instance"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifr_2a08d8fc30b64a8a9d8b9f0ec37b59c9"
                      "index$" 1
                      "kind" "param"
                      "name" "payment_iframe_id"
                      "orig" "iframe_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe/{iframeId}/instance/init"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe"
                  "{payment_iframe_id}"
                  "instance"
                  "init")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "iframeId" "payment_iframe_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "payment_iframe_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "payment_iframe"))))
      "i_frame_instance" (vs/jm
        "fields" (vs/jt)
        "name" "i_frame_instance"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifri_2a08d8fc30b64a8a9d8b9f0ec37b59c9"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "iframe_instance_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifr_2a08d8fc30b64a8a9d8b9f0ec37b59c9"
                      "index$" 2
                      "kind" "param"
                      "name" "payment_iframe_id"
                      "orig" "iframe_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe/{iframeId}/instance/{iframeInstanceId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe"
                  "{payment_iframe_id}"
                  "instance"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "iframeId" "payment_iframe_id"
                    "iframeInstanceId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"
                    "payment_iframe_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "payment_iframe"))))
      "iframe" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "ach_setting"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "allowed_parent_domain"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$ARRAY`")
              "update" (vs/jm
                "req" false
                "type" "`$ARRAY`"))
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "allowed_payment_method"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$ARRAY`")
              "update" (vs/jm
                "req" false
                "type" "`$ARRAY`"))
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "card_setting"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "click_to_pay_setting"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "currency"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "label"
            "op" (vs/jm
              "list" (vs/jm
                "req" false
                "type" "`$STRING`")
              "update" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "language"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "timeout"
            "req" false
            "type" "`$NUMBER`"))
        "name" "iframe"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifr_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "iframe_id"
                      "orig" "iframe_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe/{iframeId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe"
                  "{iframe_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "iframeId" "iframe_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "iframe_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifr_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "iframe_id"
                      "orig" "iframe_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe/{iframeId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe"
                  "{iframe_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "iframeId" "iframe_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "iframe_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account")
            (vs/jt
              "account"
              "payment_iframe"))))
      "init" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "customer"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "description"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "item"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "level2"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "level3"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "shipping_address"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "trace"
            "req" false
            "type" "`$OBJECT`"))
        "name" "init"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/payments/init"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payments"
                  "init")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "list_api_key_scopes_entry" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "category"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "description"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "enabled"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "level"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "scope"
            "req" false
            "type" "`$STRING`"))
        "name" "list_api_key_scopes_entry"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/api-key-scopes"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "api-key-scopes")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "payment_iframe" (vs/jm
        "fields" (vs/jt)
        "name" "payment_iframe"
        "op" (vs/jm
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "ifr_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "iframe_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/api/v4/accounts/{accountId}/payment-iframe/{iframeId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payment-iframe"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "iframeId" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "three_d_secure_auth" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "browser"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "card"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "challenge"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "customer"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "purchase"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "server_transaction_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "shipping"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "three_d_secure_challenge_indicator"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "three_d_secure_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "trace"
            "req" false
            "type" "`$OBJECT`"))
        "name" "three_d_secure_auth"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "tds_23d0e53de3c64e94887116da65abc8ce"
                      "index$" 0
                      "kind" "param"
                      "name" "3_d_id"
                      "orig" "resource_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 1
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/3DS/{resourceId}/browser-authenticate"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "3DS"
                  "{3_d_id}"
                  "browser-authenticate")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "resourceId" "3_d_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "3_d_id"
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "3_d"))))
      "three_d_secure_browser_init" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "acs_result_url"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "acs_url"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "cvv"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "expiry"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "pan"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "payment_details_reference"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "server_transaction_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "three_d_secure_data"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "three_d_secure_id"
            "req" false
            "type" "`$STRING`"))
        "name" "three_d_secure_browser_init"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/3DS/init-card-details"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "3DS"
                  "init-card-details")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"))))
      "three_d_secure_status" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "error"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "info"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "server_transaction_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "three_d_secure"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "three_d_secure_id"
            "req" false
            "type" "`$STRING`"))
        "name" "three_d_secure_status"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "tds_23d0e53de3c64e94887116da65abc8ce"
                      "index$" 0
                      "kind" "param"
                      "name" "3_d_id"
                      "orig" "resource_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 1
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/3DS/{resourceId}/status"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "3DS"
                  "{3_d_id}"
                  "status")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "resourceId" "3_d_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "3_d_id"
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "3_d"))))
      "transaction_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "amount"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "auth"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "card"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "customer"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "description"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "item"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "level2"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "level3"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "override"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "shipping_address"
            "op" (vs/jm
              "update" (vs/jm
                "req" false
                "type" "`$OBJECT`"))
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "status"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "timestamp"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "trace"
            "req" false
            "type" "`$OBJECT`"))
        "name" "transaction_detail"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 1861
                      "index$" 1
                      "kind" "param"
                      "name" "transaction_id"
                      "orig" "transaction_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/payments/{transactionId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payments"
                  "{transaction_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "transactionId" "transaction_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "transaction_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" 1861
                      "index$" 1
                      "kind" "param"
                      "name" "transaction_id"
                      "orig" "transaction_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{accountId}/payments/{transactionId}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "payments"
                  "{transaction_id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "transactionId" "transaction_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "transaction_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account"
              "payment"))))
      "webhook" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "event"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "url"
            "req" true
            "type" "`$STRING`"))
        "name" "webhook"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/api/v4/accounts/{accountId}/webhooks"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "webhooks")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" "120615523104"
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/webhooks"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "webhooks")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "wbh_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "webhook_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/api/v4/accounts/{accountId}/webhooks/{webhookID}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "webhooks"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "webhookID" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "wbh_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "webhook_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/api/v4/accounts/{accountId}/webhooks/{webhookID}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "webhooks"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "webhookID" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "key$" "update"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "example" 120615523104
                      "index$" 0
                      "kind" "param"
                      "name" "account_id"
                      "orig" "account_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "wbh_d193148ac2624de7b43a191682a8822f"
                      "index$" 1
                      "kind" "param"
                      "name" "id"
                      "orig" "webhook_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "PATCH"
                "orig" "/api/v4/accounts/{accountId}/webhooks/{webhookID}"
                "parts" (vs/jt
                  "api"
                  "v4"
                  "accounts"
                  "{account_id}"
                  "webhooks"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "accountId" "account_id"
                    "webhookID" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "account_id"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "account")))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinPayconex")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://api.payconex.net/"
      "entity" (vs/jm
        "account_updater" (vs/jm)
        "account_updater_schedule" (vs/jm)
        "account_updater_schedule_with_result" (vs/jm)
        "account_updater_subscription_with_result" (vs/jm)
        "account_updater_update" (vs/jm)
        "api_key" (vs/jm)
        "apple_pay_merchant_detail" (vs/jm)
        "apple_pay_session" (vs/jm)
        "dynamic_descriptor" (vs/jm)
        "i_frame_create_instance" (vs/jm)
        "i_frame_instance" (vs/jm)
        "iframe" (vs/jm)
        "init" (vs/jm)
        "list_api_key_scopes_entry" (vs/jm)
        "payment_iframe" (vs/jm)
        "three_d_secure_auth" (vs/jm)
        "three_d_secure_browser_init" (vs/jm)
        "three_d_secure_status" (vs/jm)
        "transaction_detail" (vs/jm)
        "webhook" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
